"""Add preferences table

Revision ID: abc766afa509
Revises: 66bf52ddd27e
Create Date: 2018-08-09 14:32:31.620318

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'abc766afa509'
down_revision = '66bf52ddd27e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preferences',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('dog_breed', sa.String(256), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name='preferences_pkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preferences')
    # ### end Alembic commands ###
